version: "3.7"
services:
  # Nginx Service
  nginx:
    image: library/nginx:1.19-alpine
    volumes:
      - ./project:/var/www/php:ro,delegated
      - ./Docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - phpmyadmindata:/var/www/phpmyadmin:ro,delegated
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`gevezoue.local`)
      - traefik.http.routers.nginx.entryPoints=web
    depends_on:
      - php
      - phpmyadmin
    networks:
      - frontend
      - backend

  # PHP Service
  php:
    build: ./Docker/php
    working_dir: /var/www/php
    volumes:
      - ./project:/var/www/php:delegated
    depends_on:
      - mysql
    networks:
      - backend
      - frontend

  # MySQL Service
  mysql:
    image: library/mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvz
    ports:
      - 3306:3306
    volumes:
      - ./Docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysqldata:/var/lib/mysql:delegated
    networks:
      - backend

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html:delegated
    depends_on:
      - mysql
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.drupal.rule=Host(`phpmyadmin.local`)
      - traefik.http.routers.drupal.entryPoints=web

  # Memcache Service
  memcache:
    image: library/memcached:1.6.8-alpine
    ports:
      - 11211:11211
    networks:
      - backend

# Volumes
volumes:
  mysqldata:
  phpmyadmindata:

networks:
  backend:
    internal: true
  frontend:
    name: frontend